export const TOOL_CATEGORY_OTHER = '其他';

export const TOOL_CATEGORY_ORDER = [
  '学术文献',
  '生命科学',
  '药物与化合物',
  '临床医学',
  '材料与化学',
  '地球与环境',
  '天文与空间',
  '数据处理',
  '文档处理',
  '网页与外部服务',
  '文件与执行',
  '技能与工具管理',
  TOOL_CATEGORY_OTHER,
] as const;

export type ToolCategoryZh = typeof TOOL_CATEGORY_ORDER[number];

export const PRESERVED_TOOL_TERMS = [
  'ScienceClaw',
  'ToolUniverse',
  'MCP',
  'HTTPS MCP',
  'DeepAgents',
  'sandbox',
  'arXiv',
  'OpenAlex',
  'PubMed',
  'Crossref',
  'UniProt',
  'PDB',
  'AlphaFold',
  'ChEMBL',
  'FAERS',
  'ClinicalTrials',
  'COD',
  'USGS',
  'OpenMeteo',
  'SIMBAD',
  'SDSS',
  'NASA',
  'OpenML',
  'PDF',
  'DOCX',
  'PPTX',
  'XLSX',
  'Markdown',
  'SMILES',
  'JSON',
  'JSON Schema',
] as const;

export const TOOL_CATEGORY_ALIASES: Record<ToolCategoryZh, string[]> = {
  '学术文献': ['论文', '医学论文', '文献', '预印本', '引用', '摘要', '全文', 'paper', 'article', 'literature', 'arXiv', 'OpenAlex', 'PubMed', 'Crossref'],
  '生命科学': ['蛋白', '基因', '通路', '组学', '生物', 'protein', 'gene', 'pathway', 'omics', 'UniProt', 'PDB', 'AlphaFold'],
  '药物与化合物': ['药物', '化合物', '靶点', 'ADMET', '毒性', '药物毒性', '药物安全', 'compound', 'drug', 'toxicity', 'ChEMBL', 'FAERS'],
  '临床医学': ['临床', '临床试验', '疾病', '指南', '患者', 'clinical', 'trial', 'disease', 'ClinicalTrials'],
  '材料与化学': ['材料', '化学', '晶体', '分子', '反应', '谱图', 'materials', 'chemistry', 'crystal', 'molecule', 'reaction', 'COD', 'SMILES'],
  '地球与环境': ['地震', '水文', '气候', '空气质量', '土壤', '海洋', 'earth', 'environment', 'climate', 'USGS', 'OpenMeteo'],
  '天文与空间': ['天文', '空间', '天体', '星历', '空间天气', '巡天', 'astronomy', 'space', 'SIMBAD', 'SDSS', 'NASA'],
  '数据处理': ['数据', '表格', '统计', '转换', '可视化', '机器学习', 'data', 'table', 'statistics', 'visualization', 'machine learning', 'OpenML'],
  '文档处理': ['文档', 'PDF', 'PDF 转换', 'DOCX', 'PPTX', 'XLSX', 'Markdown', '转换', '提取', 'document'],
  '网页与外部服务': ['网页', '搜索', '抓取', '第三方', 'API', 'MCP', 'web', 'search', 'crawl', 'service'],
  '文件与执行': ['文件', '命令', '执行', 'sandbox', 'file', 'command', 'execute'],
  '技能与工具管理': ['技能', '工具', '创建', '保存', '评估', '屏蔽', 'skill', 'tool', 'creator', 'evaluation'],
  [TOOL_CATEGORY_OTHER]: ['其他', '自定义', '未归类', 'other', 'custom'],
};

const SOURCE_CATEGORY_ALIASES: Record<string, ToolCategoryZh> = {
  literature: '学术文献',
  literature_search: '学术文献',
  publication: '学术文献',
  pubmed: '学术文献',
  pmc: '学术文献',
  medrxiv: '学术文献',
  biorxiv: '学术文献',
  osf_preprints: '学术文献',
  semantic_scholar: '学术文献',
  opencitations: '学术文献',
  unpaywall: '学术文献',
  europepmc: '学术文献',
  europepmc_citations: '学术文献',
  arxiv: '学术文献',
  openalex: '学术文献',
  crossref: '学术文献',
  datacite: '学术文献',
  dblp: '学术文献',
  doaj: '学术文献',
  biology: '生命科学',
  bioinformatics: '生命科学',
  protein: '生命科学',
  gene: '生命科学',
  genomics: '生命科学',
  transcriptomics: '生命科学',
  ensembl: '生命科学',
  ncbi_gene: '生命科学',
  ncbi_datasets: '生命科学',
  reactome: '生命科学',
  kegg: '生命科学',
  go: '生命科学',
  quickgo: '生命科学',
  uniprot: '生命科学',
  alphafold: '生命科学',
  pdb: '生命科学',
  rcsb_pdb: '生命科学',
  pdbe_api: '生命科学',
  string_network: '生命科学',
  drug: '药物与化合物',
  compound: '药物与化合物',
  chemistry_drug: '药物与化合物',
  pubchem: '药物与化合物',
  bindingdb: '药物与化合物',
  opentarget: '药物与化合物',
  gtopdb: '药物与化合物',
  pharmgkb: '药物与化合物',
  openfda: '药物与化合物',
  chembl: '药物与化合物',
  faers: '药物与化合物',
  admetai: '药物与化合物',
  pubchem_tox: '药物与化合物',
  clinical: '临床医学',
  clinical_trials: '临床医学',
  clinicaltrials: '临床医学',
  medicine: '临床医学',
  guidelines: '临床医学',
  clinical_guidelines: '临床医学',
  medlineplus: '临床医学',
  mesh: '临床医学',
  icd: '临床医学',
  materials: '材料与化学',
  chemistry: '材料与化学',
  molecule: '材料与化学',
  crystal: '材料与化学',
  cod_crystal: '材料与化学',
  chem_compute: '材料与化学',
  massbank: '材料与化学',
  hmdb: '材料与化学',
  lipidmaps: '材料与化学',
  zinc: '材料与化学',
  earth: '地球与环境',
  environment: '地球与环境',
  climate: '地球与环境',
  ceda: '地球与环境',
  erddap: '地球与环境',
  open_meteo: '地球与环境',
  open_meteo_climate: '地球与环境',
  open_meteo_flood: '地球与环境',
  open_meteo_marine: '地球与环境',
  usgs_earthquake: '地球与环境',
  usgs_water: '地球与环境',
  soilgrids: '地球与环境',
  waqi: '地球与环境',
  gbif: '地球与环境',
  astronomy: '天文与空间',
  space: '天文与空间',
  nasa_cmr: '天文与空间',
  nasa_donki: '天文与空间',
  nasa_eonet: '天文与空间',
  nasa_exoplanet: '天文与空间',
  nasa_ned: '天文与空间',
  nasa_sbdb: '天文与空间',
  jpl_horizons: '天文与空间',
  simbad: '天文与空间',
  sdss: '天文与空间',
  data: '数据处理',
  dataset: '数据处理',
  statistics: '数据处理',
  visualization: '数据处理',
  software_visualization: '数据处理',
  software_machine_learning: '数据处理',
  software_scientific_computing: '数据处理',
  openml: '数据处理',
  dataverse: '数据处理',
  zenodo: '数据处理',
  figshare: '数据处理',
  dryad: '数据处理',
  huggingface: '数据处理',
  document: '文档处理',
  pdf: '文档处理',
  docx: '文档处理',
  pptx: '文档处理',
  xlsx: '文档处理',
  markitdown: '文档处理',
  xml: '文档处理',
  web: '网页与外部服务',
  search: '网页与外部服务',
  mcp: '网页与外部服务',
  web_search_tools: '网页与外部服务',
  github: '网页与外部服务',
  url: '网页与外部服务',
  wikipedia: '网页与外部服务',
  wikidata_entity: '网页与外部服务',
  wikidata_sparql: '网页与外部服务',
  dbpedia: '网页与外部服务',
  file: '文件与执行',
  file_download: '文件与执行',
  execution: '文件与执行',
  python_executor: '文件与执行',
  sandbox: '文件与执行',
  skill: '技能与工具管理',
  tool: '技能与工具管理',
  tool_finder: '技能与工具管理',
  tool_composition: '技能与工具管理',
  tool_discovery_agents: '技能与工具管理',
  package_discovery_tools: '技能与工具管理',
  other: TOOL_CATEGORY_OTHER,
};

const SOURCE_CATEGORY_RULES: Array<[RegExp, ToolCategoryZh]> = [
  [/(literature|pubmed|pubtator|pmc|preprint|citation|cite|scholar|openalex|crossref|datacite|dblp|doaj|orcid|icite|fatcat|openaire)/, '学术文献'],
  [/(gene|genome|protein|proteom|pathway|reactome|kegg|uniprot|pdb|pdbe|rcsb|ensembl|ncbi|omics|cell|bio|go_|quickgo|interpro|string|hgnc|gtex|gwas|clinvar|variant|taxonomy|ortholog|wormbase|flybase|zfin)/, '生命科学'],
  [/(drug|compound|chembl|pubchem|admet|tox|faers|fda|pharm|binding|target|gtopdb|stitch|swissadme|swissdock|zinc|dose|synergy)/, '药物与化合物'],
  [/(clinical|trial|medicine|medline|guideline|disease|patient|mesh|icd|loinc|rxnorm|umls|orphanet|who|health|nhanes)/, '临床医学'],
  [/(chem|material|crystal|molecule|reaction|spect|massbank|cod_|smiles|hmdb|lipid|metabo|rhea|brenda|emolecules|enamine|mcule)/, '材料与化学'],
  [/(earth|climate|meteo|weather|flood|marine|soil|usgs|water|earthquake|environment|gbif|obis|worms|nasa_eonet|waqi|ceda|erddap|nominatim|opentopodata|worldbank|uscensus)/, '地球与环境'],
  [/(astronomy|space|nasa|simbad|sdss|jpl|exoplanet|horizons|ned|sbdb|donki|physics_astronomy)/, '天文与空间'],
  [/(data|dataset|dataverse|zenodo|figshare|dryad|openml|visualization|machine_learning|statistics|software|optimizer|summarization|huggingface|cran|anaconda|pypi)/, '数据处理'],
  [/(document|pdf|docx|pptx|xlsx|markdown|markitdown|xml)/, '文档处理'],
  [/(web|search|github|url|wiki|dbpedia|sparql|api|service)/, '网页与外部服务'],
  [/(file|download|executor|python_executor|sandbox|execute|command)/, '文件与执行'],
  [/(skill|tool|package_discovery|composition|finder|creator|evaluation|agent)/, '技能与工具管理'],
];

export const normalizeCategoryKey = (value?: string | null): string => {
  return (value || '').trim().toLowerCase().replace(/[\s-]+/g, '_');
};

export const isToolCategoryZh = (value?: string | null): value is ToolCategoryZh => {
  return Boolean(value && (TOOL_CATEGORY_ORDER as readonly string[]).includes(value));
};

export const mapToolCategoryToZh = (category?: string | null, categoryZh?: string | null): ToolCategoryZh => {
  if (isToolCategoryZh(categoryZh)) return categoryZh;
  if (isToolCategoryZh(category)) return category;
  const normalized = normalizeCategoryKey(category);
  const exactMatch = SOURCE_CATEGORY_ALIASES[normalized];
  if (exactMatch) return exactMatch;
  const ruleMatch = SOURCE_CATEGORY_RULES.find(([pattern]) => pattern.test(normalized));
  return ruleMatch?.[1] || TOOL_CATEGORY_OTHER;
};

export const getToolCategoryAliases = (categoryZh: ToolCategoryZh): string[] => {
  return TOOL_CATEGORY_ALIASES[categoryZh] || TOOL_CATEGORY_ALIASES[TOOL_CATEGORY_OTHER];
};

export const getToolCategorySortIndex = (categoryZh: ToolCategoryZh): number => {
  const index = TOOL_CATEGORY_ORDER.indexOf(categoryZh);
  return index === -1 ? TOOL_CATEGORY_ORDER.length : index;
};
